name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Flask app
        run: |
          cd ~/flask-app
          ./deploy.sh
